export {
  addAvitoDraft,
  getAvitoProfile,
  publishAvitoVacancy,
  getAvitoCatalogs,
  getAvitoSpecializationMappings,
  getAvitoExperienceMappings,
  getAvitoEmploymentMappings,
  getAvitoContractMappings,
  getAvitoSalaryPeriodMappings,
  getAvitoSalaryTaxMappings,
  getAvitoPayoutFrequencyMappings,
  getAvitoContactEmployees,
  buildAvitoPublicationRequestBody,
} from '@/utils/avitoAccount'
